(module
  (memory 1)
  (export "memory" (memory 0))
  (export "_start" (func 0))
  (export "processCart" (func 1))
  (func (;0;) (type 0))
  (func (;1;) (type 1) (param i32 i32) (result i32)
    i32.const 0)
  (type (;0;) (func))
  (type (;1;) (func (param i32 i32) (result i32))))
